from typing import Dict, Any, List, Set

# 解剖知识库
ANATOMY_RULES = {
    "lateralized": ["left", "right", "lt", "rt"],
    "paired_structures": [
        "kidney_left", "kidney_right", "adrenal_gland_left", "adrenal_gland_right", "lung_left", "lung_right",
        "temporal_lobe_left", "temporal_lobe_right", "submandibular_left", "submandibular_right", "mandible_left",
        "mandible_right", "parotid_left", "parotid_right", "mastoid_left", "mastoid_right", "tympanic_cavity_left",
        "temporomandibular_joint_left", "temporomandibular_joint_right", "tympanic_cavity_right", "eustachian_tube_left",
        "eustachian_tube_right", "middleear_left", "vestibular_semicircular_canal_left", "middleear_right",
        "vestibular_semicircular_canal_right", "eye_right", "eye_left", "hippocampus_left", "hippocampus_right",
        "optic_nerve_left", "optic_nerve_right", "lens_left", "lens_right", "head_of_femur_left", "head_of_femur_right",
        "heart_atrium_left", "heart_ventricle_left", "heart_ventricle_right", "heart_left_ventricular_myocardium",
        "heart_myocardium_left", "heart_right_atrium_blood_cavity", "heart_right_ventricle_blood_cavity",
        "heart_left_ventricle_blood_cavity", "heart_left_atrium_blood_cavity", "left_ventricular_blood_pool",
        "right_ventricular_blood_pool", "left_ventricular_normal_myocardium", "left_ventricular_myocardial_edema",
        "left_ventricular_myocardial_scars"
    ],
    "bilateral_organs": ["kidney", "lung", "adrenal", "eye", "optic_nerve", "temporal_lobe", "hippocampus", "submandibular", "parotid", "mastoid", "lens", "mandible", "head_of_femur"],
    "midline_organs": ["heart", "liver", "pancreas", "bladder", "uterus", "stomach", "esophagus", "aorta", "inferior_vena_cava", "duodenum", "spinal_cord", "brain", "trachea", "thyroid", "larynx", "brainstem", "pituitary", "optic_chiasm", "colon", "rectum", "portal_vein"],
    "always_left_structures": ["spleen"],
    "always_right_structures": ["gallbladder"],
    "spaces": ["pleural space", "pericardial space", "renal fossa", "mediastinum", "thoracic_cavity"]
}

# 病理状态词黑名单（纯器官标签禁用）
PATHOLOGICAL_STATE_WORDS = {
    "abnormal",
    "acute",
    "air",
    "atrophic",
    "atelectatic",
    "benign",
    "calcified",
    "chronic",
    "clear",
    "consolidated",
    "cyst",
    "cystic",
    "dilated",
    "diseased",
    "edema",
    "effusion",
    "emphysematous",
    "enlarged",
    "enhancing",
    "fatty",
    "fibrotic",
    "fluid",
    "healthy",
    "hemorrhagic",
    "heterogeneous",
    "homogeneous",
    "hyperdense",
    "hypodense",
    "infarction",
    "infiltrative",
    "infection",
    "inflammatory",
    "ischemic",
    "isodense",
    "large",
    "malignant",
    "metastatic",
    "necrosis",
    "necrotic",
    "no-reflow",
    "non-enhancing",
    "obscured",
    "obstructed",
    "scar",
    "sclerotic",
    "shrunken",
    "small",
    "solid",
    "thickened",
    "treated",
    "ulcerated"
}

# 病理标签关键词（允许状态描述）
PATHOLOGY_KEYWORDS = [
    "abscess",
    "aneurysm",
    "ascites",
    "atelectasis",
    "atrophy",
    "calcification",
    "collection",
    "consolidation",
    "contusion",
    "cyst",
    "density",
    "dilation",
    "edema",
    "effusion",
    "embolism",
    "fistula",
    "fracture",
    "glioma",
    "hematoma",
    "hemorrhage",
    "hydrocephalus",
    "hypertrophy",
    "infarct",
    "infection",
    "infiltrate",
    "inflammation",
    "ischemia",
    "laceration",
    "lesion",
    "mass",
    "metastasis",
    "necrosis",
    "neuroblastoma",
    "no_reflow",
    "nodule",
    "opacity",
    "osteolysis",
    "osteophyte",
    "pneumonia",
    "pneumothorax",
    "polyp",
    "rupture",
    "scar",
    "sclerosis",
    "stricture",
    "stenosis",
    "thrombus",
    "tumor",
    "ulcer",
    "varices"
]

# 有效遮挡物白名单（用于纯器官的矛盾短语）
OBSCURING_TERMS = {
    "spleen": ["bowel gas", "colonic gas", "rib shadow", "stomach shadow"],
    "kidney": ["bowel gas", "colonic gas", "rib shadow", "liver shadow", "spleen shadow"],
    "liver": ["bowel gas", "rib shadow", "lung base shadow", "heart shadow"],
    "pancreas": ["bowel gas", "stomach gas", "splenic shadow", "liver shadow", "vertebral body shadow"],
    "adrenal": ["bowel gas", "colonic gas", "rib shadow", "liver shadow", "spleen shadow", "kidney shadow"],
    "stomach": ["bowel gas", "liver shadow", "spleen shadow", "rib shadow", "lung base shadow"],
    "gallbladder": ["bowel gas", "rib shadow", "liver shadow", "duodenal gas shadow"],
    "esophagus": ["mediastinal shadow", "spine shadow", "heart shadow", "aortic shadow"],
    "bladder": ["bowel gas", "pelvic bone shadow", "uterus shadow", "prostate shadow"],
    "lung": ["rib shadow", "clavicle shadow", "scapular shadow", "mediastinal shadow", "cardiac shadow"],
    "spinal_cord": ["vertebral body shadow", "rib shadow", "metal hardware shadow", "soft tissue shadow"],
    "brain": ["skull base shadow", "petrous bone shadow", "sinus shadow", "temporal bone shadow"],
    "thyroid": ["tracheal shadow", "cervical spine shadow", "clavicle shadow", "neck soft tissue shadow"],
    "trachea": ["mediastinal shadow", "spine shadow", "heart shadow", "clavicle shadow", "thyroid shadow"],
    "larynx": ["cervical spine shadow", "mandible shadow", "thyroid shadow", "soft tissue shadow", "hyoid bone shadow"],
    "oral_cavity": ["mandible shadow", "teeth shadow", "air artifact", "tongue shadow", "maxilla shadow"],
    "brainstem": ["skull base shadow", "petrous bone shadow", "clivus shadow", "cerebellar shadow"],
    "pituitary": ["sphenoid bone shadow", "cavernous sinus shadow", "circle of Willis shadow", "temporal bone shadow"],
    "eye_right": ["orbital bone shadow", "sinus shadow", "metal artifact shadow", "eyelid shadow"],
    "eye_left": ["orbital bone shadow", "sinus shadow", "metal artifact shadow", "eyelid shadow"],
    "duodenum": ["bowel gas", "stomach gas", "liver shadow", "vertebral body shadow"],
    "colon": ["bowel gas", "colonic gas", "pelvic bone shadow", "liver shadow", "spleen shadow", "fecal matter artifact"],
    "rectum": ["pelvic bone shadow", "bladder shadow", "prostate shadow", "uterus shadow", "fecal matter artifact", "sacrum shadow"],
    "intestine": ["bowel gas", "colonic gas", "pelvic bone shadow", "liver shadow", "spleen shadow", "stomach shadow", "fecal matter artifact"]
}

NON_OVERLAPPING_COOCURRENCE = {
    # ===== 头颈部结构 =====
    "brain": ["thyroid", "larynx", "trachea", "esophagus", "aorta", "heart", "lung_left", "lung_right", "spinal_cord"],
    "brainstem": ["thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "pituitary": ["thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "optic_chiasm": ["thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "temporal_lobe_left": ["temporal_lobe_right", "thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "temporal_lobe_right": ["temporal_lobe_left", "thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "hippocampus_left": ["hippocampus_right", "thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "hippocampus_right": ["hippocampus_left", "thyroid", "larynx", "trachea", "esophagus", "spinal_cord"],
    "eye_left": ["eye_right", "spinal_cord", "colon", "rectum", "bladder"],
    "eye_right": ["eye_left", "spinal_cord", "colon", "rectum", "bladder"],
    "optic_nerve_left": ["optic_nerve_right", "spinal_cord", "colon", "rectum", "bladder"],
    "optic_nerve_right": ["optic_nerve_left", "spinal_cord", "colon", "rectum", "bladder"],
    "lens_left": ["lens_right", "spinal_cord", "colon", "rectum", "bladder"],
    "lens_right": ["lens_left", "spinal_cord", "colon", "rectum", "bladder"],
    "thyroid": ["brain", "brainstem", "pituitary", "optic_chiasm", "colon", "rectum", "bladder"],
    "larynx": ["brain", "brainstem", "pituitary", "optic_chiasm", "colon", "rectum", "bladder"],
    "parotid_left": ["parotid_right", "colon", "rectum", "bladder"],
    "parotid_right": ["parotid_left", "colon", "rectum", "bladder"],
    "submandibular_left": ["submandibular_right", "colon", "rectum", "bladder"],
    "submandibular_right": ["submandibular_left", "colon", "rectum", "bladder"],
    "mandible_left": ["mandible_right", "colon", "rectum", "bladder"],
    "mandible_right": ["mandible_left", "colon", "rectum", "bladder"],

    # ===== 胸部结构 =====
    "heart": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
              "colon", "rectum"],
    "lung_left": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
                  "colon", "rectum"],
    "lung_right": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
                   "colon", "rectum"],
    "trachea": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
                "colon", "rectum"],
    "esophagus": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
                  "colon", "rectum"],
    "aorta": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
              "colon", "rectum"],
    "inferior_vena_cava": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder",
                           "bladder", "colon", "rectum"],

    # ===== 腹部结构 =====
    "liver": ["spleen", "stomach", "pancreas", "kidney_left", "bladder", "colon", "rectum",
              "brain", "spinal_cord", "thyroid", "larynx"],
    "gallbladder": ["spleen", "stomach", "pancreas", "kidney_left", "bladder", "colon", "rectum",
                    "brain", "spinal_cord", "thyroid", "larynx"],
    "spleen": ["liver", "gallbladder", "kidney_right", "bladder", "colon", "rectum", "brain",
               "spinal_cord", "thyroid", "larynx"],
    "stomach": ["kidney_right", "bladder", "colon", "rectum", "brain", "spinal_cord", "thyroid",
                "larynx"],
    "pancreas": ["spleen", "kidney_right", "bladder", "colon", "rectum", "brain", "spinal_cord",
                 "thyroid", "larynx"],
    "kidney_left": ["liver", "gallbladder", "bladder", "colon", "rectum", "brain", "spinal_cord",
                    "thyroid", "larynx"],
    "kidney_right": ["spleen", "stomach", "pancreas", "bladder", "colon", "rectum", "brain",
                     "spinal_cord", "thyroid", "larynx"],
    "adrenal_gland_left": ["liver", "gallbladder", "bladder", "colon", "rectum", "brain",
                           "spinal_cord", "thyroid", "larynx"],
    "adrenal_gland_right": ["spleen", "stomach", "pancreas", "bladder", "colon", "rectum",
                            "brain", "spinal_cord", "thyroid", "larynx"],
    "thoracic_cavity": ["brain", "brainstem", "thyroid", "liver", "gallbladder", "spleen", "stomach", "pancreas",
                        "kidney_left", "kidney_right", "adrenal_gland_left", "adrenal_gland_right", "duodenum",
                        "portal_vein", "intestine"],

    # ===== 盆腔结构 =====
    "bladder": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "brain",
                "spinal_cord", "thyroid", "larynx", "heart", "lung_left", "lung_right"],
    "colon": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "brain",
              "spinal_cord", "thyroid", "larynx", "heart", "lung_left", "lung_right"],
    "rectum": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "brain",
               "spinal_cord", "thyroid", "larynx", "heart", "lung_left", "lung_right"],

    # ===== 其他关键结构 =====
    "spinal_cord": ["liver", "spleen", "stomach", "pancreas", "kidney_left", "kidney_right", "gallbladder", "bladder",
                    "colon", "rectum"],
    "duodenum": ["spleen", "kidney_right", "bladder", "colon", "rectum", "brain", "spinal_cord",
                 "thyroid", "larynx"],
    "portal_vein": ["spleen", "kidney_right", "bladder", "colon", "rectum", "brain",
                    "spinal_cord", "thyroid", "larynx"],

    # ===== 配对结构的安全分离 =====
    "head_of_femur_left": ["head_of_femur_right", "liver", "spleen", "kidney_left", "kidney_right", "bladder", "brain",
                           "spinal_cord"],
    "head_of_femur_right": ["head_of_femur_left", "liver", "spleen", "kidney_left", "kidney_right", "bladder", "brain",
                            "spinal_cord"],

    # ===== 心脏子结构（保持与远端器官的分离）=====
    "heart_atrium_left": ["liver", "spleen", "kidney_left", "kidney_right", "bladder", "colon", "rectum"],
    "heart_ventricle_left": ["liver", "spleen", "kidney_left", "kidney_right", "bladder", "colon", "rectum"],
    "heart_ventricle_right": ["liver", "spleen", "kidney_left", "kidney_right", "bladder", "colon", "rectum"],
    "left_ventricular_blood_pool": ["liver", "spleen", "kidney_left", "kidney_right", "bladder", "colon", "rectum"],
    "right_ventricular_blood_pool": ["liver", "spleen", "kidney_left", "kidney_right", "bladder", "colon", "rectum"],

    # ===== 前列腺 =====
    "prostate": [
        "brain",
        "brainstem",
        "optic_chiasm",
        "eye_left",
        "eye_right",
        "thyroid",
        "lung_left",
        "lung_right",
        "heart_atrium_left",
        "liver"
    ],
    "prostate_peripheral_zone": ["thoracic_cavity", "lung", "lung_left", "lung_right", "heart_atrium_left",
                                 "heart_ventricle_left", "heart_ventricle_right", "liver", "gallbladder", "spleen", "stomach", "pancreas", "kidney_left",
                                 "heart_left_ventricular_myocardium", "heart_ascending_aorta", "head_of_femur_left", "head_of_femur_right"],
    "prostate_transition_zone": [
        "brain",
        "pituitary",
        "temporal_lobe_left",
        "temporal_lobe_right",
        "parotid_left",
        "parotid_right",
        "lung_left",
        "lung_right",
        "heart_ventricle_left",
        "spleen"
    ],
    "prostate_anterior_fibromuscular_stroma": [
        "brain",
        "brainstem",
        "hippocampus_left",
        "hippocampus_right",
        "submandibular_left",
        "submandibular_right",
        "lung_left",
        "lung_right",
        "heart_ventricle_right",
        "kidney_left"
    ]
}

LESION_LOCATION = {
    "pleural_effusion": "thoracic cavity",
    "brain_tumor": "brain",
    "brain_edema": "brain",
    "brain_necrosis": "brain",
    "skin_lesion": "skin",
    "treated_aneurysm": "brain",
    "aneurysm": "brain",
    "myocardial_infarction": "heart myocardium",
    "glioma": "brain",
    "breast_tumor": "breast",
    "kidney_tumor": "kidney",
    "kidney_cyst": "kidney",
    "lung_infections": "lung",
    "liver_tumor": "liver"
}

LESION_NAME = {
    "pleural_effusion": "thoracic cavity",
    "brain_tumor": "tumor",
    "brain_edema": "edema",
    "brain_necrosis": "necrosis",
    "skin_lesion": "lesion",
    "treated_aneurysm": "aneurysm",
    "aneurysm": "aneurysm",
    "myocardial_infarction": "infarction",
    "glioma": "glioma",
    "breast_tumor": "tumor",
    "kidney_tumor": "tumor",
    "kidney_cyst": "cyst",
    "lung_infections": "infections",
    "liver_tumor": "tumor"
}
